import { Form } from '../form/form.model';
import { QuestionTypes } from '../form/question.model';
export const registrationForm: Form = {
    eventId: '',
    title: 'User Registration',
    groups: [
        {
            title: 'ข้อมูลส่วนตัว',
            description: ' Personal Information',
            order: 1,
        },
        {
            title: 'ข้อมูลการติดต่อ',
            description: 'Contact Information',
            order: 2,
        },
    ],
    questions: [
        {
            order: 1,
            group: 1,
            type: QuestionTypes.DROPDOWN,
            label: 'คำนำหน้า (ภาษาไทย)',
            key: 'title',
            choices: ['นาย', 'นางสาว', 'นาง'],
            required: true,
        },
        {
            order: 2,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'ชื่อ (ภาษาไทย)',
            key: 'firstName',
            required: true,
        },
        {
            order: 3,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'นามสกุล (ภาษาไทย)',
            key: 'lastName',
            required: true,
        },
        {
            order: 4,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'ชื่อเล่น (ภาษาไทย)',
            key: 'nickName',
            required: true,
        },
        {
            order: 5,
            group: 1,
            type: QuestionTypes.DROPDOWN,
            label: 'คำนำหน้า (ภาษาอังกฤษ)',
            key: 'titleEn',
            choices: ['Mr.', 'Ms.', 'Mrs.'],
            required: true,
        },
        {
            order: 6,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'ชื่อ (ภาษาอังกฤษ)',
            key: 'nameEn',
            required: true,
        },
        {
            order: 7,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'นามสกุล (ภาษาอังกฤษ)',
            key: 'lastNameEn',
            required: true,
        },
        {
            order: 8,
            group: 1,
            type: QuestionTypes.TEXT,
            label: 'ชื่อเล่น (ภาษาอังกฤษ)',
            key: 'nickNameEn',
            required: true,
        },
        {
            order: 1,
            group: 2,
            type: QuestionTypes.PHONE,
            label: 'เบอร์โทรศัพท์',
            key: 'tel',
            required: true,
        },
        {
            order: 2,
            group: 2,
            type: QuestionTypes.EMAIL,
            label: 'อีเมล',
            key: 'email',
            required: true,
        },
        {
            order: 3,
            group: 2,
            type: QuestionTypes.PHONE,
            label: 'เบอร์โทรศัพท์ฉุกเฉิน',
            key: 'emergencyTel',
            required: true,
        },
        {
            order: 4,
            group: 2,
            type: QuestionTypes.TEXT,
            label: 'มีความสัมพันธ์เป็น',
            key: 'emergencyRelationship',
            required: true,
        },
        {
            order: 5,
            group: 2,
            type: QuestionTypes.TEXT,
            label: 'LINE ID',
            key: 'line',
            required: true,
        },
        {
            order: 6,
            group: 2,
            type: QuestionTypes.TEXT,
            label: 'Facebook',
            key: 'facebook',
            required: true,
        },
    ],
};
